clinical_csv: clinical_df.csv
db:
- GO_Biological_Process_2021
- KEGG_2021_Human
fdr_thresh: 0.05
imputation_method: mean
mapping:
  1-C: 0
  3-A: 1
  4-S: 1
missingness_thresh: 0.2
output_dir: enrichment_results
protein_group_csv: protein_group_df.csv
protgroup_gene_map_json: protgroup_gene_map.json
var: Condition
