categorical_vars:
- Cuatom_Status
- Condition
- Custom_Sex
- Diseaseseverity
- Custom_Hypertension
- Custom_Dyslipidemia
- Custom_Active smoker
- Custom_Ever smoker
- Custom_DM
clinical_csv: ../preprocessing/clinical/clinical_df.csv
fdr_thresh: 0.05
imputation_method: mean
missingness_thresh: 0.2
output_dir: MatrixExport_NP_B
param_grid:
  n_clusters_grid:
  - 2
  - 3
  - 4
  - 5
  - 6
  umap_metrics:
  - euclidean
  - cosine
  - manhattan
  umap_min_dist:
  - 0.1
  - 0.01
  - 0.001
  umap_n_neighbors:
  - 5
  - 10
  - 15
  - 20
protein_group_csv: ../preprocessing/imputed/input_files/protein_df_MatrixExport_NP_B.csv
